version = 0.1

[default.deploy.parameters]
stack_name = "advocacia-backend"
resolve_s3 = true
s3_prefix = "advocacia-backend"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "SesFromEmail=\"lukasantonyo@gmail.com\" EmailTrabalhista=\"lukasantonyo@gmail.com\" EmailCivel=\"lukasantonyo@gmail.com\" EmailFamilia=\"lukasantonyo@gmail.com\" EmailEmpresarial=\"lukasantonyo@gmail.com\" EmailCriminal=\"lukasantonyo@gmail.com\" EmailPrevidenciario=\"lukasantonyo@gmail.com\""
image_repositories = []

[default.global.parameters]
region = "us-east-1"
